language: node_js
node_js:
  - '12'
  - '10'
  - '8'

# after_success:
#   - npm i -g semantic-release
#   - semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email: false
